### ISSUE TITLE
Build new Generator - But where? 

### ISSUE THREAD

**Issue by julianwue** [asyncapi/modelina#1025]
#### Reason/Context
I am kind of new to Electron, Node.js and NPM, was playing around for months with modelina and generator. I choose modelina for csharp and typescript code generation. In my case there is some extras I need to implement. So my plan was to just copy the csharp folder in generator and make my changes, and keep the original as it is. Then I found out there is different directorys to make a new generator and the examples and docs are very unclear. The software needs to be copied hundred times later and should be always updateable, when there is bugs or improvements in modelina.

Where should I put my new Generator? In **git-repo/src/generators** or in the **npm installed \node_modules\@asyncapi\modelina\lib\(cjs + esm + types)**? in both ways I can make my code get to work in my electron application. But what is the default and recomended way?

As far as I understood, the node command build:prod generate the folders (cjs, esm and types) and compile the code somehow. So I think its better to define it in the src and build it.

The problem is, when I generate the files and copy them to my node_modules, with the next update some of the files are overwritten and my own generator isnt working anymore. This case isn´t described or covered by documentation. The examples are also unclear if I can use npm or always have to check them out by git clone. 

I also wonder if I can choose a different folder for source of generators instead of the one I get by install with "npm install modelina"

#### Description
make it clear in the doc readme, where and how you use your amazing tools. You want to gain your users, so make the documentation better and easier to understand. Also describe the build process to make new generators and not just write, copy and look into Typescript Example. Its ways more than this... maybe someone can help me with my detailed questions because this is basics others also struggle.

**Comment by jonaslagoni** [comment]
Hey @julianwue, thanks for the question!

First of I highly recommend you to check out the `next` branch, which is right around the corner to being released as version 1. Here we documented how to create new official [generators](https://github.com/asyncapi/modelina/blob/next/docs/contributing.md#adding-a-new-generator), [input processors](https://github.com/asyncapi/modelina/blob/next/docs/contributing.md#adding-a-new-input-processor), [presets](https://github.com/asyncapi/modelina/blob/next/docs/contributing.md#adding-a-new-preset), etc!

> I choose modelina for csharp and typescript code generation. In my case there is some extras I need to implement

The whole idea of Modelina is high customization, which means it's built exactly to support your use-case of having different additions to the core generation of models. To me it does not sound like you need a new generator, but rather add custom [presets](https://github.com/asyncapi/modelina/blob/next/docs/presets.md) or [constraints](https://github.com/asyncapi/modelina/blob/next/docs/constraints.md) that will customize the rendering of models.

Let's take a few examples ([we have a bunch of examples you can check out here](https://github.com/asyncapi/modelina/tree/next/examples#examples)). 

If I wanted to change the name of the model being generated in TypeScript, [lets's say I always want to prepend](https://github.com/asyncapi/modelina/blob/next/examples/overwrite-naming-formatting/index.ts) `MyModel`, this is done through the [constraints](https://github.com/asyncapi/modelina/blob/next/docs/constraints.md):
```
const generator = new TypeScriptGenerator({
  constraints: {
    modelName: typeScriptDefaultModelNameConstraints({
      NAMING_FORMATTER: (name) => {
        return PascalCase('MyModel' + name);
      }
    })
  }
});
```
Constraints are before it reaches the presets and renders the model, [read more about the process here](https://github.com/asyncapi/modelina/blob/next/docs/input-processing.md), and [internal models](https://github.com/asyncapi/modelina/blob/next/docs/internal-model.md).

Let's say you want to add custom methods to the C# models, [then you create your own preset](https://github.com/asyncapi/modelina/blob/next/examples/include-custom-function/index.ts):
```
const generator = new CSharpGenerator({
  presets: [
    {
      class: {
        additionalContent({ content }) {
          return `${content}
public double someAdditionalFunctionForClasses()
{
        return 108.4;
} `;
        },
      }
    }
  ]
});
```
Presets are like layers you can place on top of each other, that extend the default generation process where it's possible to add or overwrite existing generated code.

Please let us know if you'd like more examples or documentation about certain topics, or want to contribute it! Hope that clarifies it, otherwise do let me know 🙂

**Comment by julianwue** [comment]
> Hey @julianwue, thanks for the question!
> 
> First of I highly recommend you to check out the `next` branch, which is right around the corner to being released as version 1. Here we documented how to create new official [generators](https://github.com/asyncapi/modelina/blob/next/docs/contributing.md#adding-a-new-generator), [input processors](https://github.com/asyncapi/modelina/blob/next/docs/contributing.md#adding-a-new-input-processor), [presets](https://github.com/asyncapi/modelina/blob/next/docs/contributing.md#adding-a-new-preset), etc!
> 
> > I choose modelina for csharp and typescript code generation. In my case there is some extras I need to implement
> 
> The whole idea of Modelina is high customization, which means it's built exactly to support your use-case of having different additions to the core generation of models. To me it does not sound like you need a new generator, but rather add custom [presets](https://github.com/asyncapi/modelina/blob/next/docs/presets.md) or [constraints](https://github.com/asyncapi/modelina/blob/next/docs/constraints.md) that will customize the rendering of models.
> 
> Let's take a few examples ([we have a bunch of examples you can check out here](https://github.com/asyncapi/modelina/tree/next/examples#examples)).
> 
> If I wanted to change the name of the model being generated in TypeScript, [lets's say I always want to prepend](https://github.com/asyncapi/modelina/blob/next/examples/overwrite-naming-formatting/index.ts) `MyModel`, this is done through the [constraints](https://github.com/asyncapi/modelina/blob/next/docs/constraints.md):
> 
> ```ts
> const generator = new TypeScriptGenerator({
>   constraints: {
>     modelName: typeScriptDefaultModelNameConstraints({
>       NAMING_FORMATTER: (name) => {
>         return PascalCase('MyModel' + name);
>       }
>     })
>   }
> });
> ```
> 
> Constraints are before it reaches the presets and renders the model, [read more about the process here](https://github.com/asyncapi/modelina/blob/next/docs/input-processing.md), and [internal models](https://github.com/asyncapi/modelina/blob/next/docs/internal-model.md).
> 
> Let's say you want to add custom methods to the C# models, [then you create your own preset](https://github.com/asyncapi/modelina/blob/next/examples/include-custom-function/index.ts) that adds additional content to the model:
> 
> ```ts
> const generator = new CSharpGenerator({
>   presets: [
>     {
>       class: {
>         additionalContent({ content }) {
>           return `${content}
> public double someAdditionalFunctionForClasses()
> {
>         return 108.4;
> } `;
>         },
>       }
>     }
>   ]
> });
> ```
> 
> Presets are like layers you can place on top of each other, that extend the default generation process where it's possible to add or overwrite existing generated code.
> 
> Please let us know if you'd like more examples or documentation about certain topics, or want to contribute it! Hope that clarifies it, otherwise do let me know 🙂

thanks for the fast reply. I already got some more informations I can use. If I have a more detailed question I will provide it the next days.

Anyway.... can you tell me how long it will take till we get a release of the next 1.0.0 final version? Didn´t find this information somewhere. Is it a matter of weeks or months?

**Comment by jonaslagoni** [comment]
> Anyway.... can you tell me how long it will take till we get a release of the next 1.0.0 final version? Didn´t find this information somewhere. Is it a matter of weeks or months?

It really comes down to a lot of variables, as am doing a lot of other tasks around AsyncAPI in general, but I am 🤞 that either before Christmas, or at the very beginning of next year.

**Comment by julianwue** [comment]
@jonaslagoni Hello Jonas,
I have big struggles with the documentation. And hope you have a second to clearify my problems. There is not even one example on how to use constrains and presets with pure JavaScript. What is my usecase because I use Electron with JS. I am now able to rewrite my enum output and include text out of x-definitions to fit my needs. Also I can inject comments into classes and enums... see this example how I did it. All changes in code are done with a preset. 

`class: {
ctor({ content }) {
const start = '// ConstructorStart'
const end = '// ConstructorEnd'
return '${start} \n${content} \n ${end}\n\n';
}}`

But there is to much changes to my well formed AsyncAPI Schema definitions right by default c# generator now. I want to use constraints to make chances. But I am not able to make any changes by code and I was debugging every part of it for now. For now I wish to completely disable all constrain logic for a language like c#. I didnt find a way, except overwrite all default settings - and I dont know how to do it.

Also I cant translate this examples [https://github.com/asyncapi/modelina/blob/next/examples/overwrite-default-constraint/index.ts](https://github.com/asyncapi/modelina/blob/next/examples/overwrite-default-constraint/index.ts) into working JS code. Can you help me, with the constraint I have to feed to my
_const generatorCSharpFile = new modelina.CSharpFileGenerator({ ..._

**Comment by jonaslagoni** [comment]
> But there is to much changes to my well formed AsyncAPI Schema definitions right by default c# generator now

Do you mind listing the things about the c# generator that does not make sense? 

> Also I cant translate this examples https://github.com/asyncapi/modelina/blob/next/examples/overwrite-default-constraint/index.ts into working JS code. Can you help me, with the constraint I have to feed to my
const generatorCSharpFile = new modelina.CSharpFileGenerator({ ...

You should be able to take the example and directly use it in JavaScript 🤔 

```ts
const generatorCSharpFile = new modelina.CSharpFileGenerator({
  constraints: {
    modelName: ({modelName}) => {
      return modelName;
    }
  }
});
```

Is there any problems you are encountering?
