### ISSUE TITLE
Feature: For Newtonsoft.Json preset use EnumMember and StringEnumConverter to serialize and deserialize enum values [CSharpGenerator]

### ISSUE THREAD

**Issue by zaytsevand** [asyncapi/modelina#1052]
#### Reason/Context
- It will allow removing many autogenerated classes: Converters, static maps from enum values to strings
- It follows a common declarative approach to defining DTO classes in C#
- Less code -- more error-prone and flexible for future change

#### Description
Simple implementation:
- https://dotnetfiddle.net/365DN6

**Comment by jonaslagoni** [comment]
@zaytsevand the problem with the declarative approach is that some specific features required by the schema formats in AsyncAPI, are simply not possible. Or two specific ones if I recall correctly.

1. Newtonsoft does not support unwrapping dictionary model properties, this means additional properties we simply don't have the property names for but knows their type. This is inherited from JSON Schema `additionalProperties` and `patternProperties` keywords.
2. Newtonsoft does not support arbitrary enum values, such as when you have a constant JSON object as enum.

I would love to simplify the approach, but with the complexity that we inherit, it's simply not possible to use the declaritive approach. It's the same problem we have in other languages.

I would probably support having a new preset that allows declaritive annotation, but then you would have to be the maintainer of it, as my main focus is incorporating the more complex custom methods. Let me know what you think and how to approach this 🙂

**Comment by zaytsevand** [comment]
> Newtonsoft does not support unwrapping dictionary model properties, this means additional properties we simply don't have the property names for but knows their type. This is inherited from JSON Schema additionalProperties and patternProperties keywords.

I don't quite get it. Could you please show an example contract or data structure that should be generated from that contract?

> I would probably support having a new preset that allows declaritive annotation, but then you would have to be the maintainer of it, as my main focus is incorporating the more complex custom methods. Let me know what you think and how to approach this 🙂

I would love to, as well as for Pydantic preset in Python. I can also help with C# features in the future if needed :) 
Based on my practice, declarative is the dominant way to implement dotnet contracts, so I think it could be another way around for developers who work with this stack: we won't use arbitrary values and stick to strings.

**Comment by jonaslagoni** [comment]
If you have an input such as this (or indirectly in AsyncAPI or OpenAPI):
```json
const jsonSchemaDraft7 = {
  $schema: 'http://json-schema.org/draft-07/schema#',
  type: 'object',
  additionalProperties: true,
  properties: {
    email: {
      type: 'string',
      format: 'email'
    }
  }
};
```

Where `additionalProperties` is used, it means there must exist a way to add extra properties, where we don't know the property names, but only their types. 

The way we enable this at the moment, is to create a property for it that is a dictionary with a [serialization type `unwrap`](https://github.com/asyncapi/modelina/blob/cf0307fb1c22a2b39713d766796a6bd2532ecf91/src/models/ConstrainedMetaModel.ts#L143). This means that the serialization of such a model must not be:

```json
{ "additionalProperties": { "MyCustomProp": 42 }, "email": "my@email.com" }
```

but instead:

```json
{ "MyCustomProp": 42, "email": "my@email.com" }
```

Because this is what the JSON Schema deems as valid.

> Based on my practice, declarative is the dominant way to define dotnet contracts, so I think it could be another way around for developers who work with this stack

The methods in C# are not really meant to be used in your development, because the serialization of the model still happens the same way regardless of whether you use declarative way or custom converters. All serialization of the models is still:

```csharp
JsonConvert.SerializeObject(message);
```

So it's not something you notice (or should). It's just our way of ensuring the right data gets serialized. This is also why I dont see the benefit in having the declarative annotation along side a custom serializer (or maintaining both), as it would be providing less value than what the current preset does 🙂 But if you want it you can have it, that's the point with presets! 😆  

Hope all that made sense, otherwise, let me know!

**Comment by zaytsevand** [comment]
@jonaslagoni makes total sense. Thanks for the explanation. Declarative would probably outperform a custom serializer, but it's unlikely that anyone concerned about performance would use Newtonsoft.Json anyway. If I'm not mistaken, Newtonsoft is considerably slower than the built-in version. Also, the maintainer of Newtonsoft previously noted that he wouldn't support asynchronous serialization and deserialization: again, not the best bet in terms of performance.
So making a separate preset for Newtonsoft just for the people who don't want their DTOs to be populated by a custom converter makes little sense.
P.S. while we're on a topic, that `additionalProperties` thing in contracts is kinda self-defeating :) You either want a contract declaration or a dynamic structure. I get a scenario when a developer may want a dynamic map, but I feel like it would have been more logical to have it as an option, not a default. I'm currently disabling it everywhere, basically.

**Comment by jonaslagoni** [comment]
> P.S. while we're on a topic, that additionalProperties thing in contracts is kinda self-defeating :) You either want a contract declaration or a dynamic structure. I get a scenario when a developer may want a dynamic map, but I feel like it would have been more logical to have it as an option, not a default. I'm currently disabling it everywhere, basically.

It really depends on the AsyncAPI contract tbh, cause in some scenarios you have both. We dont try to guess what developers want, but rather follow what the standards allow. That will always be the default way, because that is unopinionated, that is the standard that we must follow 🙂

But, that said, we should definitely provide ways for developers to choose to disable or change behaviors unwanted in code. 

Which is why in certain scenarios you might want to use declaritive and disable additionProperties entirely.

**Comment by zaytsevand** [comment]
> Which is why in certain scenarios you might want to use declaritive and disable additionProperties entirely. If people ask for such a feature of course 😄
I would be happy to have the option to disable `additionalProperties` completely without annotating every model in a schema. But I can't see it happening since the default is to enable them.
