### ISSUE TITLE
The direction of the (default) presets

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/modelina#111]
While integrating this library into [ts-nats-template](https://github.com/asyncapi/ts-nats-template/pull/53) I got frustrated because my expected outcome was not aligned with the default preset. And this comes down to my basic understanding of it was wrong, the setup is great because it offers many different ways of rendering a model. However, I realized that we need a clear direction in which way we want to take these presets.

As I see it we have 3(+) choices in which our default preset could move towards:

1. The complete model
1. The data transfer model
1. The minimalistic
1. Do you have another suggestion?

## The complete model
This model gives you everything in regards to rendering a complete model. Where you have access to not only the properties but additionalProperties, patternProperties, inheritance, etc.

## The data transfer model
Optimized for serializing and deserializing data. 

## The minimalistic
Just the bare minimum properties, basically what we have now.

## Questions 
- What should the default preset be?
- What presets should we include with this library by default?
    - How many different presets should the library provide? I.e. all 3 before-mentioned presets?
    
## Related issues and PRs
All the following issues/PRs are blocked until we figure out the direction.
- https://github.com/asyncapi/generator-model-sdk/issues/68 and PR https://github.com/asyncapi/generator-model-sdk/pull/71
- https://github.com/asyncapi/generator-model-sdk/issues/107
- https://github.com/asyncapi/generator-model-sdk/issues/43

The following issues/PRs are somewhat blocked since this could trigger a rewrite unless we are careful.
- https://github.com/asyncapi/generator-model-sdk/issues/49
- https://github.com/asyncapi/generator-model-sdk/issues/48
- https://github.com/asyncapi/generator-model-sdk/issues/47

**Comment by magicmatatjahu** [comment]
Hi!

> How many different presets should the library provide? I.e. all 3 before-mentioned presets?

As many as the community will want. I mean, we're currently rendering a very minimalist model (as you noticed yourself). This is due to the fact that we render models in libraries for the first time and we find bugs/problems. For me this is fine - not bugs 😅 but problems, yes, they helps us to check that if we are going the right way.

In general when implementing presets I meant creating a system that you are able to overwrite everything if you want - if you have such a case. You can imagine that when rendering clients or parsers, we will have to change the default preset from scratch to render the model as expected. 

If we will have a few official default presets for each language, it's also not a problem - the user will be able to use one. The problem may arise how to merge the default presets with other, additional presets. I mean how to make generic common presets to fit every default preset. I will not answer you because we do not have too many tested use cases to find out if everything works properly and if it is used in the best way.

> Optimized for serializing and deserializing data.

We can use currently default preset and write serialization, deserialization methods by custom preset.

> This model gives you everything in regards to rendering a complete model. Where you have access to not only the properties but additionalProperties, patternProperties, inheritance, etc.

Rendering `additionalProperties`, `patternProperties` shouldn't be a problem when you implement `additionalProperties` preset. For inheritance we must find way to adjust only name part of class, so yes, make inheritance by preset at the moment is possible only by rewrite default preset.

**Comment by fmvilas** [comment]
> 1. The complete model
> 1. The data transfer model
> 1. The minimalistic

I feel like I'm missing some context here. Don't completely follow you here.

**Comment by jonaslagoni** [comment]
At the moment the renderer we have implemented (gonna use Java as an example) contains two default presets for `ClassRenderer` and `EnumRenderer`. 

If we look at the `ClassRenderer` it calls different presets in its path based on what is being rendered. For a constructor, the `ClassRenderer` calls the preset named `ctor` when it wants to render it. The default preset for this is to not render any constructor.

Now to reflect back to the different suggestions of default presets. Should you render additionalProperties by default? Jackson annotation? `toString`, `hashcode` methods? Constructor? Basically what is the default output when you don't customize any presets.

`The minimalistic` would be exactly like it is now, where only properties for the class are rendered alongside encapsulation.

`The data transfer model` would focus on adding annotations by default instead of raw properties with encapsulation.

`The complete model` is to render everything possible. This includes rendering correct inheritance, additionalProperties, patternProperties, constructor, helper methods whatever we find useful.

Now, this is only a matter of what the **default** preset should render right out the box, that does not mean that we wont have presets which does this differently. And this is where the next question in line comes in `What presets should we include with this library?`

**Comment by derberg** [comment]
> What presets should we include with this library?

do we have to stick to only one set of presets? For example, for me, default is almost always minimalistic and I would go with answer : `minimalistic`. But just want to make sure we are open here and if over time we find out there is a place for other "official" Java presets that we also add them to a library or store them as a separate module

**Comment by jonaslagoni** [comment]
@derberg we have to stick to a default preset if we want the library to work out of the box without any options sat. But yes presets can be partially rewritten or created from scratch. There is really no limit.

> But just want to make sure we are open here and if over time we find out there is a place for other "official" Java presets that we also add them to a library or store them as a separate module 

This is also a question, what should the structure of the preset folders look like (where should we store them), who maintains them if they will be inside the library, ..., in general we have a lot of questions we need to answer in regards to how we want to manage and maintain presets 😅

**Comment by derberg** [comment]
sound to me like we should be minimalistic first then, and next step to start using them -> discover what is missing -> what has to be added -> if there is a point to have multiple different presets per language -> etc. So basically answers will come once we start using them

**Comment by magicmatatjahu** [comment]
> If we look at the ClassRenderer it calls different presets in its path based on what is being rendered. For a constructor, the ClassRenderer calls the preset named ctor when it wants to render it. The default preset for this is to not render any constructor.

This is not a true :) It renders constructor, but return undefined, it means that if someone wants to render constructor, then can extend class by one implementation for `ctor` preset like:

```ts
{
  class: {
    ctor() {
      return `constructor() {...logic }`
    }
  }
}
``` 

it may be a bug that we are not rendering constructor.

> Now to reflect back to the different suggestions of default presets. Should you render additionalProperties by default? Jackson annotation? toString, hashcode methods? Constructor? Basically what is the default output when you don't customize any presets.

I know that you mention at the end of your comment, that it could be also rendered in separate presets, but why we need this features in defaultPreset? I don't think so that we should render by default not needed in basic app annotations - e.g. in Spring yes, but then as I wrote, we can use presets like here https://github.com/asyncapi/generator-model-sdk/blob/4d3df7cdb8919a7c85e6fa70346fd810e82ce65a/src/generators/java/presets/ConstraintsPreset.ts

Also related to `The data transfer model` and `The complete model` presets. By JS nature, we can create this `defaultPresets` by extending minimalistic preset - yes we can do that 😄

**Comment by jonaslagoni** [comment]
> This is not a true :) It renders constructor, but return undefined, it means that if someone wants to render constructor, then can extend class by one implementation for ctor preset like:

@magicmatatjahu I mean that is what I am saying, it is only that our default preset for the class does not do so. No one questions that anything is possible to do and it can be customized in multiple ways to support any scenario you have. 

What I am suggesting is that we need to define what the `default preset` should render in the end. 

I have noticed that we are talking past each other a bit, so let me clarify the terms I have used based on @magicmatatjahu docs:
- `default preset` this is what is by default rendered for classes, enums, interfaces etc also called a preset in it self, just the default one used. - https://github.com/asyncapi/generator-model-sdk/blob/master/docs/customisation.md#overriding-the-default-preset
- `preset hook`/ `preset method` this is the specific preset hooks that the renderer calls at different times in the rendering process. This for example is `ctor` for when the class renderer wants to render the constructor of a class. -https://github.com/asyncapi/generator-model-sdk/blob/master/docs/customisation.md#java
- `preset` this is the collection of preset hooks and their callbacks that determines the output. - https://github.com/asyncapi/generator-model-sdk/blob/master/docs/customisation.md#preset

**Comment by magicmatatjahu** [comment]
@jonaslagoni I'm not on the topic, is this issue still relevant?

**Comment by magicmatatjahu** [comment]
@jonaslagoni I'm not on the topic, is this issue still relevant?

**Comment by jonaslagoni** [comment]
I think we can close it. The default presets always (and should) provide the model that closest represents the input data, any additional functions, wrappers, etc, are to be added by the user of the library.
