### ISSUE TITLE
Add support for records with the C# generator through an option

### ISSUE THREAD

**Issue by henrikjon** [asyncapi/modelina#1153]
#### Reason/Context
Please try answering few of those questions
- Why we need this improvement?
  - Records is a popular way of defining DTO's in C#
- How will this change help?
  - It gives more flexibility for C# users
- What is the motivation?
  - Records are a great match for DTO's in C#:
    - Reference based records are immutable by default using short declaration, ex: `public record Car(int Doors, string Manufacturer);`
    - Made for containing data, not for logic
    - They use value based comparison

#### Description
Please try answering few of those questions
- What changes have to be introduced?
- Will this be a breaking change?
- How could it be implemented/designed?

**Comment by jonaslagoni** [comment]
After discussing [this in slack](https://asyncapi.slack.com/archives/CQVJXFNQL/p1678694504438039), we think the best approach is to do a similar thing we did for TypeScript and interface/class, where [we conditionally render one or the other](https://github.com/asyncapi/modelina/blob/109ceff4a7721bbfb0b625ddd33a6725cab46c3d/src/generators/typescript/TypeScriptGenerator.ts#L219).

So to achieve this in the C# generator we need to do the following changes:
1. We add a model type option as typescript which is either `class` by default or `record`. 
2. Create a new `RecordRenderer`, you can use the [class renderer](https://github.com/asyncapi/modelina/blob/master/src/generators/csharp/renderers/ClassRenderer.ts) as starting point.
3. The new renderer should have the following hooks: `self`, `property`, `additionalContent`
4. `self` should render the full syntax, not the shorthand one, for the simple reason its easier to add custom functions and handle in general with no penalty. So the hook should return:

```
public record ${model.name}
{
  ${render all properties}
  ${render additionalContent}
};
```
so it should look like this: 
```
public record Person
{
    public required string FirstName { get; set; }
    public required string LastName { get; set; }
};
```
7. `property` should return `public ${property.required ? 'required ' : ' '}${property.type} ${property.name} { ${render getter} ${render setter} }` so it assembles `public required string FirstName { get; set; }`
6. `getter` should just return `get;`
8. `setter` should just return `init;`
9. `additionalContent` should not return anything.
10. Change the generator to conditionally use the [record renderer instead of class renderer](https://github.com/asyncapi/modelina/blob/109ceff4a7721bbfb0b625ddd33a6725cab46c3d/src/generators/csharp/CSharpGenerator.ts#L196) based on the type option added in step 1.

How does that sound to you @henrikjon?

**Comment by jonaslagoni** [comment]
Awesome, looking forward to it @henrikjon! 

Let me know if I can help with anything 🙂

**Comment by henrikjon** [comment]
@jonaslagoni thanks! Thats very generous, I have working code with a snapshot test but might still have a couple of things to iron out that i have not discovered yet. Trying to get a bit more familiar with the codebase before i submit the pull request. 

I did however create a local draft in my fork: https://github.com/henrikjon/modelina/pull/1 . All feedback is very welcome :)
