### ISSUE TITLE
Expose documentation in the website

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/modelina#1161]
#### Reason/Context
Currently, all the documentation is only located under [./docs](https://github.com/asyncapi/modelina/tree/master/docs), however, they should be visible on the website as well to make it more accessible.

I am not 100% sure how to achieve this but here is how I think it can be achieved:
- First you have to add a script that copies all the ./docs files into the website directory, so they are exposed under `modelina.org/docs`.
- Then you need to figure out how to render those markdown files inside react. You might need to add additional meta data inside the markdown files for it to work.
- The docs page need to have a side menu that contains a link to all the documentation pages.

It is entirely fine that it's a rough first draft that we can improve over time.

**Comment by Savio629** [comment]
Does async api render markdown files on docs page?
@jonaslagoni

**Comment by jonaslagoni** [comment]
@Savio629 it does yes! 

Might be a good place to start 👍

**Comment by akshatnema** [comment]
> Does async api render markdown files on docs page?

Yes @Savio629, website renders the docs in the JSX form built on top of markdown files. You can add the docs of modelina into the website using a Github workflow, You can take reference of generator docs workflow - https://github.com/asyncapi/generator/blob/master/.github/workflows/update-docs-in-website.yml and make it for modelina too.

**Comment by jonaslagoni** [comment]
@akshatnema we are not talking about embedding the docs in the modelina website 🙂 So we got all the docs here in this repo, we just want to know how markdown files are being embedded into the current AsyncAPI website, so we can do the same here: https://github.com/asyncapi/modelina/tree/master/modelina-website

**Comment by Savio629** [comment]
@akshatnema 
How should I start implementing this feature?

**Comment by akshatnema** [comment]
Hey @Savio629 sorry for the late response :pray:.

So, basically on the website, docs are part of routes inside `pages` folder as per next js. But we aren't treating it as routes inside the website. They are retrieved from the posts.json file (made on the build time of the website) on the basis of slug. Every page in the docs or blog contains a slug which is the relative route of the page according to the website. You can view that process in the [`DocsLayout`](https://github.com/asyncapi/website/blob/master/components/layout/DocsLayout.js) and [`Layout`](https://github.com/asyncapi/website/blob/master/components/layout/Layout.js) components.

Also, the markdown files are converted to JSX using [`gray-matter`](https://www.npmjs.com/package/gray-matter). The script for the above is https://github.com/asyncapi/website/blob/master/scripts/build-post-list.js. The posts.json file is made using this script and it is a JSON object containing "docs", "blog", "job", etc. object that contains all the data related to the particular page in the form of an array of objects. For docs and blogs, certain metadata is stored for each page so that additional information related to page can be set in the component if provided.

**Comment by Savio629** [comment]
Just a quick update,
It is taking me more time than I expected to understand the codebase of async website's docs page.
@jonaslagoni do we need to replicate the same structure of async website or I can try it from scratch (It will behave the same as converting markdown and then rendering it on website).
Apologies for the delayed response.
PS : I'll continue this after a week or two as I have my exams going on right now...

**Comment by jonaslagoni** [comment]
Feel free to solve the problem as you wish @Savio629, it was only a suggestion and a good reference implementation :)

**Comment by jonaslagoni** [comment]
Hey @Savio629 just checking in whether you are stuck on something? 🙂

**Comment by Savio629** [comment]
Actually I was busy with my exams and I had to take a pause from this.
I'll update you with the feature in few days.

**Comment by jonaslagoni** [comment]
@Savio629 I am assuming you dropped pursuing this and opening it up for other contributors 🙂 

cc @SumantxD @Shurtu-gal @kaushik-rishi maybe one of you are interested? 🙂

**Comment by Shurtu-gal** [comment]
Sure @jonaslagoni let me draft a approach and after getting suggestions I can start working on it.

**Comment by Savio629** [comment]
I've been quite occupied with my involvement in GSoC and a few other commitments lately. I apologize for not communicating this earlier.
@Shurtu-gal  Let me know if you have any questions or need any assistance regarding the project...

**Comment by Shurtu-gal** [comment]
@jonaslagoni, from what I can gather till now is that we can use [Docs Generator](https://github.com/asyncapi/website/blob/master/scripts/build-post-list.js) to build the docs and render it using [DocsLayout](https://github.com/asyncapi/website/blob/cf59cd86a47c54ff003a6db25f151d25984873b1/components/layout/DocsLayout.js.). Then we can generate new docs upon updation by a GitHub action. 

How does this sound? Feel free to suggest some changes. 😃

**Comment by jonaslagoni** [comment]
@Shurtu-gal yep, you are basically right, but instead of the last part with the action, we just add it as part of our build script in Modelina, same way we have for examples 🙂
