### ISSUE TITLE
C# generator add xml docs from the async api description

### ISSUE THREAD

**Issue by diogonborges** [asyncapi/modelina#1330]
#### Reason/Context
Please try answering few of those questions
- Why we need this improvement?
To not lose information (from a documention perspective) in the process of generating C# models
- How will this change help?
Improve the C# generation to be more complete
- What is the motivation? 
We're using this on our project to generated C# contracts for the models

#### Description
Please try answering few of those questions
- What changes have to be introduced?
Unsure
- Will this be a breaking change?
No
- How could it be implemented/designed?
Unsure

**Comment by jonaslagoni** [comment]
@diogonborges can you give an example model i.e. the output you are looking for?

**Comment by jonaslagoni** [comment]
This issue is similar to how the other languages work in terms of adding descriptions: https://modelina.org/playground?tsIncludeDescriptions=true

This means we have to utilize the functionality of xmldoc: https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/xmldoc/?redirectedfrom=MSDN

What we are looking to generate is a description per model and property:

```csharp
namespace asyncapi.models
{
    using System.Collections.Generic;
    /// <summary>
    /// The light measured payload
    /// </summary>
    public class LightMeasured
    {
        /// <summary>
        /// Id of the streetlight.
        /// </summary>
        private int? id;

        /// <summary>
        /// Light intensity measured in lumens.
        /// </summary>
        private int? lumens;

        /// <summary>
        /// Date and time when the message was sent.
        /// </summary>
        private string? sentAt;

        private Dictionary<string, dynamic>? additionalProperties;

        public int? Id
        {
            get { return id; }
            set { id = value; }
        }

        public int? Lumens
        {
            get { return lumens; }
            set { lumens = value; }
        }

        public string? SentAt
        {
            get { return sentAt; }
            set { sentAt = value; }
        }

        public Dictionary<string, dynamic>? AdditionalProperties
        {
            get { return additionalProperties; }
            set { additionalProperties = value; }
        }
    }
}
```

We can do this through [presets](https://modelina.org/docs/presets), you can follow this guide to add it: https://github.com/asyncapi/modelina/blob/master/docs/contributing.md#adding-a-new-preset

You can use the following existing description preset for TS as reference: https://github.com/asyncapi/modelina/blob/master/src/generators/typescript/presets/DescriptionPreset.ts

**Comment by xaviergxf** [comment]
This makes a lot of sense
Can this be reopened?
