### ISSUE TITLE
Enable TS input

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/modelina#187]
#### Reason/Context
It would be awesome to take TS code and be able to output models in any other language.

#### Description
There already exist libraries we can leverage to minimize the effort to integrate this where we could use the already existing JSON Schema process or create a custom one.

Link shared by Kevin Swiber: https://github.com/YousefED/typescript-json-schema

**Comment by jonaslagoni** [comment]
Gonna let this issue run out, even though I would love to enable it, it's just not time at the moment.

**Comment by ron-debajyoti** [comment]
Hey @jonaslagoni  let me take this up, even though it's not marked as a good-first-issue .

I kinda got tired of modifying docs and now want to try to solve some core issues.

**Comment by jonaslagoni** [comment]
> Hey @jonaslagoni let me take this up, even though it's not marked as a good-first-issue .
> 
> I kinda got tired of modifying docs and now want to try to solve some core issues.

Please do! 👏

Feel free to ping me with any questions you may have 🙂

**Comment by ron-debajyoti** [comment]
Hey @jonaslagoni, could you clarify a few things for me w.r.t the issue and correct me if I misunderstood anything ? 

Since currently we support input of AsyncAPI, JSON Schema and output data models of various languages like JS, Java, Go. 
- For this issue, we are trying to support the input of a Typescript data model and output the existing supported language ?
- We are going to implement it by first converting the input Typescript model to  JSON schema using the custom library mentioned above ?  And then use the obtained JSON schema to output the language supported data model ?

**Comment by jonaslagoni** [comment]
> For this issue, we are trying to support the input of a Typescript data model and output the existing supported language?

Yes, basically converting it to our internal model representation yes. So we can output it to multiple other languages 🙂 

> We are going to implement it by first converting the input Typescript model to JSON schema using the custom library mentioned above? And then use the obtained JSON schema to output the language-supported data model?

That is my suggestion yes 🙂 I.e. you "basically" do the same as the AsyncAPI input processor (and the other input processors tbh 😄) where it uses the JSON Schema input processor to convert the message payloads into the internal model representation (CommonModel) here: https://github.com/asyncapi/modelina/blob/88cf92df862bbac8e8606b3b7b5d9f6967683b12/src/processors/AsyncAPIInputProcessor.ts#L34
