### ISSUE TITLE
Improve typings in project

### ISSUE THREAD

**Issue by magicmatatjahu** [asyncapi/modelina#50]
We should improve typings in whole project to improve DX:

- [x] improve generic types in `AbstractGenerator`, `AbstractRenderer` - https://github.com/asyncapi/generator-model-sdk/pull/60
- [ ] improve generic types in presets: `CommonPresets...` and in `Preset` abstract interface to include typings for options for given preset.

**Comment by jonaslagoni** [comment]
@magicmatatjahu I am assuming this is still relevant?

**Comment by jonaslagoni** [comment]
We also have a problem with CommonModel sharing types with JSON Schema, such as for example `type`. 

From the perspective of CommonModel types should ONLY be an array if length > 1, otherwise it will be a simple type. This restriction is not present in the Schema class. I think we have to remove the sharing of properties completely from the Schema class.

Thoughts @magicmatatjahu ?

**Comment by magicmatatjahu** [comment]
> This restriction is not present in the Schema class.

Schema extends the CommonSchema where type have signature `type?: string | string[];`

Probably I don't understand the problem.

**Comment by jonaslagoni** [comment]
When a Schema is interpreted, the type are `string` if it is a simple type, and `string[]` if it is multiple types (union types). This restriction of the types are not easy to document and from the generator's perspective hard to know about.

**Comment by magicmatatjahu** [comment]
@jonaslagoni I'm not on the topic, is this issue still relevant?

**Comment by jonaslagoni** [comment]
#365 should address the issue, closing.
