### ISSUE TITLE
Special cases in enum values fails to generate unique enum keys

### ISSUE THREAD

**Issue by panwauu** [asyncapi/modelina#504]
#### Describe the bug
Some Edge-cases can lead to duplicate keys in enums. Given the schema:
```json
{ "enum": ["test plus", "test+"] } 
```
It would generate the enum output
```ts
export enum X {
  TEST_PLUS = "test plus",
  TEST_PLUS = "test+"
}
```

### Proposed solution
After generation check the generated keys and add the index on duplicates.
Proposed output:
```ts
export enum X {
  TEST_PLUS_0 = "test plus",
  TEST_PLUS_1 = "test+"
}
```

This can still lead to duplicates in other edge cases.
```json
{ "enum": ["test plus", "test+", "test plus 0"] } 
```
```ts
export enum X {
  TEST_PLUS_0 = "test plus",
  TEST_PLUS_1 = "test+",
  TEST_PLUS_0 = "test plus 0",
}
```

This could be applied iteratively until there are no more duplicates to ensure a valid ts output in all cases.
```json
{ "enum": ["test plus", "test+", "test plus 0"] } 
```
```ts
export enum X {
  TEST_PLUS_0_0 = "test plus",
  TEST_PLUS_1 = "test+",
  TEST_PLUS_0_1 = "test plus 0",
}
```

Another option could be to use random numbers or UUIDs. Then the result would be different on each render which is not a good option i guess.

### Related
Issue #450 (Some discussion on how naming in enums should work), PR #497

**Comment by jonaslagoni** [comment]
Definitely, a "problem" that we should solve. Not sure I like the index approach, as it is rather hard to know from a user standpoint what is what. In my mind, the key that is most notably changed i.e. `test+`, needs to make sure it has no conflicts, it is not the others that have to adapt.

In your example:
```json
{ "enum": ["test plus", "test+", "test plus 0"] } 
```

My first assumption is that the keys for the enums are the ones that most accurately represent their value. I.e. the two entries are straightforward and should not be tampered with:
```
export enum X {
  TEST_PLUS = "test plus",
  TEST_PLUS_0 = "test plus 0"
}
```

The last entry, because we alter its key from `TEST+` to `TEST_PLUS` it is up to this key to fit within the existing entries.

I.e. generate something like `TEST_PLUS_RESERVED`, and continue to do this until no conflicts are found.

What do you think about this approach? 🤔

**Comment by panwauu** [comment]
This would be a nicer approach.
It would require a more complex implementation as we need to determine the priority of the keywords.
As this is an edge case I would also consider it valid to just go for the simplest solution available to provide valid output in all cases even if it is suboptimal for these edge cases.
Probably everything else is just _overengineering_?

**Comment by quadrrem** [comment]
What about just throwing an error in case there are duplicate keys when rendering the enum? 
It's kind of "fail-fast", not too complex to implement and will "solve" all possible edge cases.

You just have to ensure that the message is descriptive enough to point to the offending key in the api definition (and also the fact that a potential normalization has happened)

**Comment by jonaslagoni** [comment]
> What about just throwing an error in case there are duplicate keys when rendering the enum?

That could also be an option 🤔 

This scenario is only triggered because we constrain the keys to the language, and in that case, we might end up with duplicate keys. Failing the generation, because something we did not handle correctly, is bad UX 😅 Cause it is not the user of the library that did something wrong.

**Comment by jonaslagoni** [comment]
This should already be solved in the `next` branch.
