### ISSUE TITLE
[📑 Docs]: Modelina Add Docs for Model generation other than AsyncAPI

### ISSUE THREAD

**Issue by boyney123** [asyncapi/modelina#605]
### What Dev Docs changes are you proposing?

I wasn't aware from the tool homepage and examples on AsyncAPI that Modelina could generate code bindings for anything other than AsyncAPI.

Looking in the GitHub repo I can see the project description "Library for generating data models based on inputs such as AsyncAPI, OpenAPI, or JSON Schema documents", which is quite clear, and also in the README I can see docs how to generate models from JSON/OpenAPI.

I wonder if we should add this information to the tool homepage too? https://www.asyncapi.com/tools/modelina

Think it's a great feature and would be nice to talk about it and maybe even extend the code examples to render OpenAPI and JSON Schemas code from it.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jonaslagoni** [comment]
Thanks for raising the issue @boyney123, I considered it as when I created the page. However, to keep it simple and directly targeted AsyncAPI community I left it out. Definitely, something that would be great to have!

**Comment by ritik307** [comment]
@boyney123 @jonaslagoni I would like to work on this issue 😊

**Comment by Dule-mart** [comment]
Hello, @boyney123 and @jonaslagoni, if this issue is still open, would it be assigned to me so I could work on it if @ritik307 has not yet fixed it.

**Comment by derberg** [comment]
@Samridhi-98 @ron-debajyoti @magicmatatjahu hey folks since Jonas is out for few days and you are also codeowners, maybe you have some ideas for @Dule-mart 

IMHO it is completely fine to add a paragraph of info to https://www.asyncapi.com/tools/modelina that Modelina supports more than AsyncAPI. There are OpenAPI and other examples here https://github.com/asyncapi/modelina/tree/master/examples so I assume it is mainly about https://www.asyncapi.com/tools/modelina

More improvement to the Playground are scoped here https://github.com/asyncapi/modelina/issues/636

**Comment by magicmatatjahu** [comment]
We can add information about other supported formats other than AsyncAPI, but let's not extend this issue with a features from https://github.com/asyncapi/modelina/issues/636 - here we should only do description updates.

**Comment by derberg** [comment]
yes yes, definitely #636 is separate work, related to some coding as part of AsyncAPI Mentorship

in this issue we talk about simple fix contribution to docs, I guess just another paragraph after this one -> https://github.com/asyncapi/website/blob/56536dee006c95f6271e118a13e2ebe615110af5/pages/tools/modelina.js#L253-L255

**Comment by Dule-mart** [comment]
After going through the comment here and the issue raised, I was thinking the paragraph should be added before this "Sometimes you just want to generate data models for your payload."

Since that paragraph will be defining Modelina as a "Library for generating data models based on inputs such as AsyncAPI, OpenAPI, or JSON Schema documents"

I'm adding the paragraph before but if it is not ok, I can change it back to the suggestion made by @derberg

**Comment by ron-debajyoti** [comment]
> After going through the comment here and the issue raised, I was thinking the paragraph should be added before this "Sometimes you just want to generate data models for your payload."

I think this works great. But it's also important to note that most of the supported schemas are AsyncAPI, JSON, and OpenAPI. The support for TypeScript files  is still limited and is a work in progress :sweat_smile: 


> I'm adding the paragraph as a description to modelina, I can change it back to the suggestion made by @derberg if this doesn't seattle well with anyone.

This works fine from my side.

**Comment by jonaslagoni** [comment]
Solved in https://github.com/asyncapi/website/pull/775
